version: '3.4'

services:
  memsql:
    image: 'memsql/cluster-in-a-box'
    ports:
      - 3306:3306
      - 8080:8080
    environment:
      LICENSE_KEY: ${LICENSE_KEY}
      ROOT_PASSWORD: ${ROOT_PASSWORD}
      START_AFTER_INIT: 'Y'