version: '2'

services:
  memsql:
    image: 'memsql/cluster-in-a-box'
    volumes:
    - ./sqlSchema/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 3306:3306
      - 8080:8080
    environment:
      LICENSE_KEY: ${LICENSE_KEY}
      ROOT_PASSWORD: 'RootPass1'
      START_AFTER_INIT: 'Y'